Task1. V.2_a
sergey-berezin/s02170142 pull request #2
Opened 2020-09-30 19:04 UTC by HIDDENDEN

Добрый день Сергей Борисович! У меня возник вопрос в ходе выполнения лабораторной работы. Как средство синхронизации использовал IAsyncEnumerable. И при попытке протестировать вывод результатов на экран, по мере их поступления, у меня постоянно одинаковая цепочка вывода. Хотя потоки и processid разные, это я проверил. Не подскажите, в чем может быть дело? Мне кажется, что может yield return как-то последовательно добавляет элементы в Stream. Заранее спасибо

2020-10-04 19:19 UTC, sergey-berezin requested changes
.onnx файл присутствует в двух экземплярах.

2020-10-04 19:19 UTC, sergey-berezin commented on ImgProcLib/ImageProcClass.cs
> +                     int idx = (int)pi;
Можно передавать имя файла вместо номера задачи.

2020-10-04 19:19 UTC, sergey-berezin commented on ImgProcLib/ImageProcClass.cs
> +             {
Странный отступ.

2020-10-04 19:19 UTC, sergey-berezin commented on ImgProcLib/ImageProcClass.cs
> +                resultTaskArray[i] = await Task<String>.Factory.StartNew(pi =>
Принципиальная ошибка: нет параллельности (ответ вопрос в PR). Код после await продолжится только после ЗАВЕРШЕНИЯ задачи.

2020-10-04 19:19 UTC, sergey-berezin commented on ImgProcLib/ImageProcClass.cs
> +        public static async IAsyncEnumerable<String> GetRecognitionAsync(int numOfFiles, String[] filePaths)
Возвращение строки с текстовым сообщением - не самым лучший API. Неудобно разбирать результат распознавания программно.

2020-10-04 19:19 UTC, sergey-berezin commented on ImgProcLib/ImageProcClass.cs
> +                yield return resultTaskArray[i];
Результат для i-й задачи будет возвращён только когда выполнится i-1.

Посмотрите обсуждение здесь: https://stackoverflow.com/questions/58194212/how-to-implement-an-efficient-wheneach-that-streams-an-iasyncenumerable-of-task

2020-10-06 19:16 UTC, HIDDENDEN commented
Исправил недочеты

2020-10-12 08:37 UTC, sergey-berezin approved these changes

2020-10-12 08:37 UTC, merged